# Generated by Django 3.2.5 on 2021-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_name_userbase_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='town_city',
        ),
        migrations.AddField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userbase',
            name='town',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address_line1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='address_line2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
