# Generated by Django 3.2.5 on 2021-07-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_basket_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
