# Generated by Django 3.2.5 on 2021-08-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
    ]
