# Generated by Django 3.2.5 on 2021-08-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
