# Generated by Django 3.2.5 on 2021-08-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basket',
            name='size',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
