# Generated by Django 3.2.5 on 2021-08-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_title'),
        ('basket', '0002_auto_20210821_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='item',
        ),
        migrations.AddField(
            model_name='basket',
            name='items',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
